# Generated by Django 5.2.17 on 2026-09-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('location_name', models.CharField(blank=True, max_length=180)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('welcome_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding/%Y/%m/')),
                ('guest_name', models.CharField(blank=True, max_length=70)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('emoji', models.CharField(choices=[('heart', '❤️'), ('love', '😍'), ('touched', '🥹'), ('sparkle', '✨')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='events.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'is_approved', '-created_at'], name='events_phot_event_i_fb3363_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('photo', 'session_key', 'emoji'), name='unique_session_reaction'),
        ),
    ]
