# Generated by Django 5.2.17 on 2026-09-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='events_phot_event_i_fb3363_idx',
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('ceremony', 'Cerimônia'), ('party', 'Festa'), ('dance-floor', 'Pista'), ('friends', 'Amigos'), ('family', 'Família')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'is_approved', '-created_at', '-id'], name='photo_gallery_idx'),
        ),
        migrations.AddField(
            model_name='uploadattempt',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_attempts', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='uploadattempt',
            index=models.Index(fields=['event', 'session_hash', '-created_at'], name='upload_session_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadattempt',
            index=models.Index(fields=['event', 'ip_hash', '-created_at'], name='upload_ip_idx'),
        ),
    ]
