# Generated by Django 5.2.17 on 2026-09-22 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_uploadattempt_alter_photo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Usuários (noivos/casal) com acesso ao painel deste evento e moderação das fotos.', related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Usuários com acesso ao painel'),
        ),
    ]
